### ISSUE TITLE
Not working with bootstrap

### ISSUE THREAD

**Issue by fabiohvp** [SilverMira/angular-snowpack-plugin#8]
I am using https://github.com/aloatias/TodoList.Front to test your plugin and I couldn't make it run using "snowpack dev" or "npx ngsnow", I got the following error:

[snowpack] [404] /node_modules/bootstrap/dist/css/bootstrap.min.css

This project is not mine, it uses ng-bootstrap and runs fine when using "ng serve".

**Comment by SilverMira** [comment]
Fixed by 2cca420e8d377866adbc697881691b8d7b6dccb8 which will be included in `2.3.1`. 
Feel free to reopen the issue if needed.

**Comment by fabiohvp** [comment]
It is compiling fine now and it detects file change (including in the browser console log) but changes are not applied and I need to reload the page manually
